# Site setings
name: 'JeffTadashi'
description: 'Network/Cybersecurity Specialist'
meta_description: 'Some description here'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'jeff-atlanta.jpg'
  greetings: "Hi there! I'm Jeff, and welcome to my world..."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://jefftadashi.com/
# disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: github-web-contact-form@jefftadashi.com
contact_page_description: "Have any questions, requests? Feel free to leave me a note here. -Jeff"
thankyou_page_description: "Your message has been successfully sent. I'll get back to you as soon as I can!"

# Social links
twitter: 'jefftadashi'
# facebook: 'username'
github: 'JeffTadashi'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
linkedin: 'jeff-tadashi-moy'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About Me
    url: /bio
#  - text: Style Guide
#    url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
